
[functions.reminder]
enabled = true
verify_jwt = true
import_map = "./functions/reminder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reminder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reminder/*.html" ]

[functions.send-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-push/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-push/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-push/*.html" ]

[functions.get-ranking]
verify_jwt = false

[functions]

[functions.link-auth-user]
enabled = true
verify_jwt = true
import_map = "./functions/link-auth-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/link-auth-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/link-auth-user/*.html" ]

[functions.register-init]
verify_jwt = false
entrypoint = "./functions/register-init/index.ts"

[functions.hello-ping]
verify_jwt = false
entrypoint = "./functions/hello-ping/index.ts"
